### PR TITLE
Expose `Proof::add_to_batch` in public API

### PR DESCRIPTION
**Pull request by str4d**
This supports downstream users that want more control over how proof batches are processed, instead of just batch validating Orchard bundles with `orchard::bundle::BatchValidator`.

### CODE REVIEW

**Review by daira — APPROVED** [review]
utACK

**Comment by str4d** [comment]
@dconnolly is going to test that this works for `zebra`, and if it is sufficient then I will merge this and make an `0.2.1` release PR.

**Comment by dconnolly** [comment]
This seems to be working!

One more request, we cannot get the params or raw plonk verifying key out of `VerifyingKey`, can we add `fn params(self) -> Params` and `fn vk(self) -> plonk::VerifyingKey` to `orchard::circuit::VerifyingKey`? Right now I'm testing by regenerating them as in `build()`

**Review by nuttycom — APPROVED** [review]
utACK

**Comment by str4d** [comment]
> One more request, we cannot get the params or raw plonk verifying key out of `VerifyingKey`, can we add `fn params(self) -> Params` and `fn vk(self) -> plonk::VerifyingKey` to `orchard::circuit::VerifyingKey`?

@dconnolly I don't want to expose these APIs in the `orchard` crate. I'd rather add an API to `VerifyingKey` that can accept a `halo2_proofs::plonk::BatchVerifier`. But I suspect that may not suit your `Service` usage in `zebrad`? In which case, you should likely just continue to do what you are currently doing, namely duplicating the three or four lines from inside `VerifyingKey::build()`.

**Pull request merged**
